name: examples

on:
  push:
    paths: ['**.foxil']
    branches: [main]
  pull_request:
    paths: ['**.foxil']
    types: [opened, synchronize]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Build V
        run: |
          make
          sudo ./v symlink

      - name: Checkout blux source code
        uses: actions/checkout@v2
        with:
          path: foxil
    
      - name: Build Foxil
        run: |
          cd ./foxil
          make

      - name: Run examples
        run: |
          cd ./foxil
          make run-examples
